name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PRODUCT_ID: ${{ secrets.VERCEL_PRODUCT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environement Information
        run: vercel pull --yes --environment=preview --token =${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{secrets.VERCEL_TOKEN}}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{secrets.VERCEL_TOKEN}}
